melizeche/ayudapy

- templates/home.html
- templates/info_give.html
- templates/info_request.html
Signed-off-by: Felipe Hermosilla <felihermosilla@gmail.com>
> Improving some of the call to action text

- core/views.py
- templates/base.html
- templates/request.html
---Changelog---
views.py > Add fallback favicon to thumbnail when there is no picture
base.html > Add meta data for the previews and new blocks for the fields to change
request.html > Add field change for each request
> Add social media previews for FB and TW issue #3

- core/models.py
- Eliminamos como se solicito el `blank=True` del campo `address` para que sea requerido.
> src: Hacer que address sea requerido en el formulario issue #28

- core/models.py
> Telefono acepta solo numeros, address field is requerido

- conf/settings.py.example
- conf/urls.py
- core/serializers.py
- core/views.py
> add serializers.py and basic stuff for django rest framework

- README.md
- conf/settings.py.example
- conf/urls.py
- core/models.py
- core/serializers.py
- core/views.py
- requirements.txt
> Merge dev into master

- templates/base.html
- templates/list.html
I implemented what #47 suggests. The implementation is quite simple, but it does the job :)
> Use a DataList element to display cities

- core/views.py
- templates/request.html
Se elimina mensaje de confirmación de guardado de pedido que estaba repetido
> Mensaje de confirmación repetido.

- conf/urls.py
- templates/contact_us.html
- templates/footer.html
> Create a basic contact us page

- templates/list.html
> Consume geoJSON data from the API

- core/models.py
- templates/contact_us.html
- templates/footer.html
- templates/includes/bulma_form.html
- templates/info_give.html
- templates/info_request.html
Cambios meramente cosméticos: corrección de acentos y puntuación.
> Cosmetic fixes

- README.md
Actualizamos la lista de Contribuyentes en el README.md
> doc: Actualizamos lista de Contributors en README.md

- templates/includes/buttons.html
> se agregan colores a los iconos de redes sociales

- core/views.py
- templates/request.html
> link to contact by whatsapp in request.html

- core/serializers.py
To add timestamp in results objects
```json
"results": [
{
...
"added": "2020-04-08T23:32:57.445240-04:00"
}
]
```
> Add "added" field to HelpRequestSerializer

- templates/contact_us.html
> change css buttons of contact_us.html

- core/views.py
> mejoras en texto de enlace al Whatsapp

- templates/contact_us.html
- templates/footer.html
link to youtube channel in footer.html and add email contact in contac.html
> link to youtube channel in footer.html and add email contact

- static/scripts/list.js
- templates/base.html
- templates/list.html
We now use AJAX to load the requests on the map. Both the map and the table shows the same data, thus the request to the backend is made only
once.
I also refactored the code in list.html. The JavaScript part is now in the static/scripts/list.js.
Eventually, we should obfuscate and minimize all the JS.
> requests page refactor

- templates/contact_us.html
- templates/footer.html
> CAMBIO DE LINK DE REDES HOT FIX

- conf/settings.py
- core/models.py
**Prioridad:** baja
**Tipo:** performance
Descripción en issue #152
> Added *args and **kwargs to HelpRequest.save()

- .github/workflows/cd_test_env.yml
- conf/api_urls.py
- conf/urls.py
- core/api.py
- core/serializers.py
1. Fixed some API missing fields
2. Added API to add device
3. You can add HelpRequest through API now.
> Some new stuff

- core/views.py
- templates/list.html
> Remove unnecessary queries from list_request

- templates/contact_us.html
- Arreglamos el signo + en el correo de contacto
CC: @melizeche
> Corregimos el mail de contacto que tenian un signo +

- templates/help_request_form.html
- Agregamos botón fullscreen al mapa de solicitar y unificamos código `javascript` en una sola etiqueta `<script></script>`
> Agregamos fullscreen a solicitar y unificamos una estiqueta <script>

- static/scripts/list.js
* set default zoom to 14
* grouping threshold is < 13
* min_zoom = 11
> hotfix: update grouping threshold in the requests list page

- core/models.py
- templates/help_request_form.html
- Agregamos geoinversa a la solicitud
> Agregamos geoinversa a la solicitud

- static/scripts/list.js
> hotfix: grouping threshold increased

- conf/api_urls.py
- conf/urls.py
- org/api.py
- org/serializers.py
- org/views.py
- static/scripts/list-donation.js
- templates/donation.html
- templates/includes/share_buttons_donation.html
- templates/list_donation.html
- templates/list_donation_by_city.html
Closes #177 
Endpoints agregados:
* api/v1/donationcenters/
* api/v1/donationcentersgeo/
> src: Vista de centros de donacion #177

- core/views.py
- Corrección que impide que se vote varias veces a favor o en contra sobre un pedido por el mismo usuario.
> Validación para que no se vote varias veces

- templates/list.html
Replaces anchor tags with button to prevent firing event listeners
> replace anchor with button tags

- templates/list.html
We just unify master and dev again.
> Sync master and dev

- core/serializers.py
We reduced the properties that we return as part of the JSON object.
refs #186
> /helprequestsgeo with minimum properties

- static/scripts/list.js
- templates/list.html
* Cambiamos el color del icono Mi ubicación a verde, para diferenciar de los pedidos.
Muestra:
> Cambiamos el color del icono Mi ubicación a verde.

- core/views.py
- Se agregó una condición que soluciona el inconveniente.
> Validación para que no se vote varias veces fix bug al crear cookie

- templates/footer.html
In order to make list-item fully clickable
> Removes li tags in footer

- templates/list_by_city.html
- Se modifico para que por defecto muestra los puntos agrupados en lista ciudad.
> En la vista ciudad, por defecto estan agrupados los puntos

- .gitignore
- README.md
- conf/settings.py
- requirements.txt
- static/scripts/leaflet-patch.js
- static/scripts/list-donation.js
- static/scripts/list.js
- templates/base.html
- templates/list.html
- templates/list_donation.html
We now are able to minify and version static files using django-pipeline (when DEBUG=False).
**In the production and development servers we need to install yuglify as indicated in the README file.**
refs #230
> We add django-pipeline to manage static assets

- templates/donation.html
Missing phone number in donation view
> add rendered phone_number to donation center

- README.md
Add dependencies. Update contribution tips. Added missing contributors (some still have no name).
> Update dependencies, contributing tips and contrbutors

- templates/base.html
> Change host url function for social sharing image

- core/models.py
- org/models.py
Removes whitespaces in **phone** field for **DonationCenter** and **HelpRequest**  models
> Removes whitespaces in phone number

- static/scripts/list-donation.js
Reemplaza texto Donación por Centro en los popups del mapa
> Reemplaza texto Donación por Centro

- static/scripts/list-donation.js
- static/scripts/list.js
Yuglify does not support ES6 :(
> replace const for var to avoid crushing yuglify

- conf/settings.py
- static/scripts/table-view.js
- templates/donation_center/list.html
- templates/help_request/list.html
The TableView class was not found due to a missing "export"
> fix: export TableView

- core/models.py
> Prevent duplicates to show

- templates/footer/contact_us.html
- templates/footer/general_faq.html
- templates/volunteer/form.html
fix breadcrum home links in volunteer form, general_faq and contact_us views
> fix breadcrum home links

- templates/base.html
In order to show the logo in tweets
> Add https to content in og:image metatag

- templates/help_request/details.html
mantiene el logo en el metatag og:image en details.html de help_request
> mantiene el logo en el metatag og:image

- conf/urls.py
- templates/home.html
- templates/volunteer/form.html
- templates/volunteer/info.html
Added a legal disclaimer and updated url references
> Add a legal disclaimer for volunteers form

- static/scripts/table-view.js
In order to prevent XSS injection
Reference article: [https://vanillajstoolkit.com/helpers/sanitizehtml/](url)
> Add sanitizeHTML function

- conf/settings.py
- conf/urls.py
- requirements.txt
In order to log unauthorized access attempts.
> Add admin_honeypot

- conf/api_urls.py
- core/api.py
- core/serializers.py
I am not sure if this is a reasonable way to do it but here it goes.
I added `/api/v1/cities` to eventually use in #167
> Add cities API

- conf/api_urls.py
- core/api.py
> add stats endpoint

- README.md
- core/views.py
- templates/help_request/post.html
Fixed issues with selected categories when a help request has a validation error
1. Selected categories are not displayed 
2. Selected categories cannot be unselected after form validation
- **Before validation error**
- **After validation error**
> Remember selected categories after form validation

- core/views.py
- templates/donation_center/list_by_city.html
- templates/help_request/list_by_city.html
The vulnerability is originated from views that use "autoescape off"
https://github.com/melizeche/ayudapy/blob/9298272c647ca9c1293a4581ac092720554075d9/templates/donation_center/list_by_city.html#L101
https://github.com/melizeche/ayudapy/blob/9298272c647ca9c1293a4581ac092720554075d9/templates/help_request/list_by_city.html#L103
Now those views use ajax queries to load maps content
Ref: [https://code.djangoproject.com/wiki/AutoEscaping](url)
> Fix vulnerable to XSS views 

- locale/es/LC_MESSAGES/django.po
> stats: fix i18n message

- static/scripts/list-donation.js
- static/scripts/list.js
Sending a tentative solution to prevent that the user's location marker gets duplicated on the map.
> fix for issue #270

- templates/footer/footer.html
- templates/home.html
Remove Red Cross logo and comment out buttons re: org app
> Remove/comment CR logo
